### ISSUE TITLE
checkpoint_path = Path("./ckpt/") 该目录下的大模型文件以及config.json缺失

### ISSUE THREAD

**Issue by shencp** [xinchen-ai/Westlake-Omni#2]
如题，目录下的内容缺失导致无法正常启动，我在fishaudio/fish-speech-1.4下找到目标文件，但是config.json的配置项跟代码不匹配，请问在哪可以直接获取ckpt目录下的压缩包？

**Comment by zaiji100** [comment]
遇到相同的问题：
$ python gradio_demo.py
Traceback (most recent call last):
  File "/opt/soft/llm/Westlake-Omni/gradio_demo.py", line 12, in <module>
    vqm = load_vqgan(checkpoint_path, device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/soft/llm/Westlake-Omni/generate.py", line 372, in load_vqgan
    state_dict = torch.load(ckpt_path / "firefly-gan-vq-fsq-8x1024-21hz-generator.pth")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/english/miniconda3/envs/westlakeOmni/lib/python3.11/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/english/miniconda3/envs/westlakeOmni/lib/python3.11/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/english/miniconda3/envs/westlakeOmni/lib/python3.11/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/firefly-gan-vq-fsq-8x1024-21hz-generator.pth'

**Comment by hooxing** [comment]
一样出现了

**Comment by jimmyken** [comment]
一样，大模型文件缺失。

**Comment by wfs2018** [comment]
https://huggingface.co/xinchen-ai/Westlake-Omni
